### ISSUE TITLE
What are the attributes stored in each point?

### ISSUE THREAD

**Issue by NhanTran96** [hkust-vgd/pointwise#17]
I could interpret the data structure of each **.hdf5** file as follows:

- data field: shape(N, 4096, 12)

- label field: shape(N, 4096)

where N denotes the number of blocks each contains 4096 points sampled from that particular block; 12 is the number of attributes stored in each point. 

I know that the first three attributes are X,Y,Z coordinates. What about the rest of it? Do they imply anything?

And one more question. What tool or package did you use to visualize the point clouds?
![image](https://user-images.githubusercontent.com/18115563/63220181-e6163580-c1b4-11e9-8995-f71a36a9feb8.png)

**Comment by songuke** [comment]
Regarding the format, according to this evaluation script, it should be xyz
normal color global_xyz.
https://github.com/scenenn/pointwise/blob/master/scene_seg/eval_scene_seg_scenenn.py
The global_xyz is used for merging all the blocks into a global scene.

Thanks.

2019年8月18日(日) 11:03 Nhan <notifications@github.com>:

**Comment by NhanTran96** [comment]
That should be clear enough. 

Regarding the visualization, what package did you use to view the point clouds?

**Comment by pqhieu** [comment]
We used our in-house visualisation tool to view the point clouds.
You can achieve the same results using Phong shading and screen space ambient occlusion.

Take a look at [Open3D](http://www.open3d.org) too.

Thanks.

**Comment by NhanTran96** [comment]
> We used our in-house visualisation tool to view the point clouds.
> You can achieve the same results using Phong shading and screen space ambient occlusion.
> 
> Take a look at [Open3D](http://www.open3d.org) too.
> 
> Thanks.

Thank you very much.
